### ISSUE TITLE
Fails when given too many PNGs?

### ISSUE THREAD

**Issue by hassankhan** [aslansky/css-sprite#20]
I'm trying to use this with my project [emojify.js](https://github.com/hassankhan/emojify.js) and I need to pass it a large number of PNGs to output to base64-encoded images. 

My task:

```js
gulp.task( 'styles', function() {

    return gulp.src( 'images/emoji/*.png' )
        .pipe( sprite( {
            prefix : 'emoji emoji-',
            base64 : true,
            style  : 'emojify.min.css'
        } ) )
        .pipe( cssmin() )
        .pipe( gulp.dest( config.path.dist ) );

} );
```

My output log:
```bash
[11:33:15] Using gulpfile /Volumes/Data HD/Dropbox/Projects/emojify.js/gulpfile.js
[11:33:15] Starting 'styles'...

/Volumes/Data HD/Dropbox/Projects/emojify.js/node_modules/css-sprite/lib/css-sprite.js:115
n(opt.cssPath, sprite.relative) : 'data:' + imageinfo(sprite.canvas.toBuffer()
                                                                    ^
Error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
    at createStyle (/Volumes/Data HD/Dropbox/Projects/emojify.js/node_modules/css-sprite/lib/css-sprite.js:115:106)
    at DestroyableTransform.createSprite [as _flush] (/Volumes/Data HD/Dropbox/Projects/emojify.js/node_modules/css-sprite/lib/css-sprite.js:164:78)
    at DestroyableTransform.<anonymous> (/Volumes/Data HD/Dropbox/Projects/emojify.js/node_modules/css-sprite/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)
    at finishMaybe (/Volumes/Data HD/Dropbox/Projects/emojify.js/node_modules/css-sprite/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (/Volumes/Data HD/Dropbox/Projects/emojify.js/node_modules/css-sprite/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at DestroyableTransform.Writable.end (/Volumes/Data HD/Dropbox/Projects/emojify.js/node_modules/css-sprite/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
    at DestroyableTransform.onend (/Volumes/Data HD/Dropbox/Projects/emojify.js/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:180:16)
```

**Comment by Matrosskin** [comment]
It is still reproducible for me because there is to many src png - 882 images.

**Comment by aslansky** [comment]
Ok I'll try to reproduce the issue.

**Comment by Matrosskin** [comment]
I use images from https://github.com/frissdiegurke/emoji-parser-bower

**Comment by aslansky** [comment]
Hey @Matrosskin I know its a long time but by now [sprity](https://github.com/sprity/sprity) is the successor of css-sprite. I tried sprity with a lot of icons (over 6000). And it worked pretty well. So if you still need that give it a try.
