### ISSUE TITLE
gaze@0.6.4 error when installing

### ISSUE THREAD

**Issue by mcometa** [aslansky/css-sprite#49]
**UPDATE**
Just for the record, gaze@0.6.4 does not support node v0.12.0 that's why I am having the errors below. I downgraded to v0.11 and the install went successful. Thanks!

---

Not sure what's happening here but while installing your NPM, I am having some install errors. Any idea? The log is below.
Node stuff:
```
$ node -v
v.0.12.0
$ npm -v
2.5.1
```
Error log:
```
> gaze@0.6.4 install /usr/local/lib/node_modules/css-sprite/node_modules/gaze
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/pathwatcher/src/main.o
In file included from ../src/main.cc:21:
In file included from ../src/common.h:26:
../node_modules/nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
...
...
...
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/pathwatcher/src/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/css-sprite/node_modules/gaze
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "css-sprite"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! gaze@0.6.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gaze@0.6.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the gaze package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls gaze
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /xxxxxxxxxxxxxx/xxxxxx/xxxxxxx/xxxxxx/npm-debug.log
FAIL: 1
```

**Comment by savaa** [comment]
Yep, I have the same issue. Use VisualStudio Express 2012 and VisualStudio Express 2013 (different machines).

**Comment by mcometa** [comment]
If same error with gaze 0.6.4 then @savaa you have to downgrade to v0.11 nodejs. gaze0.6.4 does not support the new version of node yet.

**Comment by christophehurpeau** [comment]
Gaze only seems to be used in cli.js, do you think it could be possible to split this module to have one without gaze as a dependency ?
